### ISSUE TITLE
Selectable templates by having a directory each?

### ISSUE THREAD

**Issue by o-jasper** [kumavis/ethereum-simulator#20]
I [tried](https://github.com/o-jasper/ethereum-simulator/commit/c6cb4a47ee6c283903001ce44e87cfa3c2253272) to make each directory a set of templates, but so far it is creating weird bugs.

The bugs seem to care between `other_function(functional_function());` and `var a=functional_function(); other_function(a);`, the former giving an error. Programming languages should in principle not care about that... The latter gives memory leaks issues..

Could do the same as with `assets/`...

Just like my other issue, probably low priority.

**Comment by k1n0k0** [comment]
Ah there's some magic going on here. `fs.readFileSync` needs a string literal for the filepath, because the files' contents are actually inlined, replacing the `fs.readFileSync` call.

This magic is provided by [brfs](https://github.com/substack/brfs). Thats the only magic at work, i'm pretty sure. sorry for the confusion!

**Comment by o-jasper** [comment]
Right... It is essentially macro-ifies the function so browsers can handle it.. Glad i didnt push too hard, it would have taken me too much time to find out myself.. Thanks for the reponse :) I should have looked at documentation about it.

Strangely i do see you can use a parameter `__dirname`, and add it, not found yet how to use those though. If you could you'd only need to change one parameter; `'./templates/default/blala'` you'd do `__templates + 'blabla'`.

**Comment by k1n0k0** [comment]
`__dirname` is provided by node, so I think it is looking for that variable explicitly. 

Here is the brfs is regarding [dynamic require statements](https://github.com/substack/brfs/issues/9)

**Comment by k1n0k0** [comment]
I'm going to close this issue, but I'm happy to continue the discussion.

**Comment by o-jasper** [comment]
Browserify has this argument. 

> --insert-global-vars, --igv
>  Comma-separated list of global variables to detect and define.
>     Default: __filename,__dirname,process,Buffer,global

Beefy should be able to pass that along. So in the `"start"` entry of `package.json`, i put `beefy app.js:bundle.js --open --live -- --insert-global-vars __filename,__dirname,process,Buffer,global,__templateFiles -t brfs` It doesnt work if i put the definition `var __templateFiles='./templates/default/'` in `lib/view.js`, but it crashes if i put it in;

```
 /home/jasper/oproj/coin/ethereum/ethereum-simulator/node_modules/browserify/node_modules/insert-module-globals/index.js:82
            var value = vars[name](file, basedir);
                                  ^
 TypeError: Property '__templateFiles' of object #<Object> is not a function
at /home/jasper/oproj/coin/ethereum/ethereum-simulator/node_modules/browserify/node_modules/insert-module-globals/index.js:82:39
```

Edit: totally okay with it being closed. Otherwise the open issue list grows unmanagably..

**Comment by k1n0k0** [comment]
At some point I will move to a more dynamic build system and then this part should be easier to deal with.
