### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by guaka** [kumavis/ethereum-simulator#23]
MIT makes most sense

**Comment by o-jasper** [comment]
Or the opposite road; AGPL...

But GPL gives more leverage, forcing giving back code, and for instance in dual licensing.(which requires agreement from all contributors, just  k1n0k0, right now. I suppose tiny edits could possibly matter less) and it doesnt stop anyone else also using GPL. Was never really convinced by 'it is incompatible with such and such license', and sometimes it is literally just closed source developpers wanting a free lunch incorporating BSD/MIT licensed code into their own, where they cant with GPL. (If you make people pay for your software i make you pay for mine) Of course they migth be _right_ if they ask for LGPL.

Probability of dual licensing is really low, of course. Particularly, 'closed source cryptocurrency' sounds like a bad idea.

**Comment by k1n0k0** [comment]
Added an MIT license
