### ISSUE TITLE
trace execution

### ISSUE THREAD

**Issue by benjaminbradley** [kumavis/ethereum-simulator#24]
Would it be possible to get a trace of the code execution as part of the output?
I'm imagining source line (with line number) on the left and corresponding evaluation and result on the right.

**Comment by kumavis** [comment]
If you can find an example of this being done with js, im sure we can implement it

**Comment by benjaminbradley** [comment]
I didn't realize it was executing within the browser's javascript context. Just opening developer tools provides some good insight.

**Comment by kumavis** [comment]
yeah, you could even throw a debugger statement into your contract
